"""Annual reservoir reports for every New Mexico reservoir in catalog/reservoirs.yaml.

For each reservoir: how much water it held each year, how full that was against the pools the
operator actually defines, how much flood storage it used, and how much water came in and went
out. Every capacity is the one in force that year, recovered from the record where the operator
has since replaced its table.

    uv run python scripts/reservoir_fill.py            (or: just reports)
    uv run python scripts/reservoir_fill.py --only cochiti abiquiu
    uv run python scripts/reservoir_fill.py --no-notes

Writes
    reports/reservoir_annual_fill.csv        every reservoir-year
    reports/reservoir_capacity_eras.csv      every capacity-table era, with capacity per pool
    reports/reservoir_pools.csv              pool definitions and where they came from
    reports/reservoirs/<key>_annual_fill.csv one per reservoir
    docs/reports/reservoirs/<key>.md         one notes file per reservoir (generated; edit the
                                             registry text, not the file)

Reads only the DuckDB catalog, the NID CSV archived under data/grids/nid, and the registry. No
network calls. Needs `nmwater fetch usace_cwms --kind ratings --kind levels` and a catalog build.

Method (docs/reports/reservoir-fill.md has the long version)
  1. Capacity table. The operator's current elevation-to-storage table from CWMS
     (reservoir_ratings), validated by reproducing reported storage from reported elevation
     after the table's effective date.
  2. Pools. Top of conservation, top of flood control and so on from CWMS location levels,
     or a full-pool elevation given in the registry with its evidence. Pools are elevations;
     their capacity is looked up in the table, so it changes when the table does.
  3. Eras. Where reported storage departs from the current table at the same elevation, an
     older table was in force. Years are compared only over the elevation band they share,
     because the departure varies with elevation. Each era's capacity at each pool elevation is
     the current table plus that era's departure there, measured locally when the lake was at
     that level during the era and extrapolated when it was not.
  4. Monotone. Capacity at a fixed elevation can only fall, as sediment accumulates. A weighted
     pool-adjacent-violators fit enforces that per pool, with measured capacities pinned.
"""

from __future__ import annotations

import argparse
import math
from itertools import pairwise
from pathlib import Path

import duckdb
import pandas as pd
import yaml

from nmwater.derived.reservoirs import (REGISTRY, SOURCE_CITES, build, dry_threshold, load_nid)

ROOT = Path(__file__).resolve().parents[1]




# ---------------------------------------------------------------------------- data access
def connect(db: str):
    con = duckdb.connect(db, read_only=True)
    con.execute("SET TimeZone='UTC'")
    return con
































# ---------------------------------------------------------------------------- notes
def _fmt(x, nd=0):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return f"{x:,.{nd}f}"


def render_notes(con, r: dict, nid: dict) -> str:
    k, cfg = r["key"], r["cfg"]
    n = nid.get(cfg.get("nid_id"), {})
    L = [f"# {cfg['name']}", "",
         "_Generated by `scripts/reservoir_fill.py` from `catalog/reservoirs.yaml`. Edit the registry, "
         "not this file._", "", cfg["summary"].strip(), "",
         f"Report: `reports/reservoirs/{k}_annual_fill.csv`. Regenerate with `just reports`. "
         "Shared method and column definitions: [../reservoir-fill.md](../reservoir-fill.md).", ""]
    if k == "elephant_butte":
        L += ["The curated, hand-reviewed treatment of this reservoir, with its full capacity history, is "
              "[../elephant-butte-fill.md](../elephant-butte-fill.md).", ""]

    def nv(c):
        v = n.get(c)
        return None if v is None or (isinstance(v, float) and math.isnan(v)) else v

    L += ["## Dam at a glance", "", "| | |", "|---|---|",
          f"| Dam | {cfg['dam']} |", f"| River | {cfg['river']} |", f"| Basin | {cfg['basin']} |",
          f"| Owner | {_owner(nv('Owner Names'))} ({nv('Primary Owner Type') or 'n/a'}) |"]
    if nv("Federal Agency Involvement Operation"):
        L.append(f"| Operated with | {nv('Federal Agency Involvement Operation')} |")
    L += [f"| Dam type | {str(nv('Dam Types') or 'n/a').replace(';', ', ')} |",
          f"| Purposes, per the dam registry | {str(nv('Purposes') or 'n/a').replace(';', ', ')} |",
          f"| How it is operated | {ROLE_TEXT[cfg['role']]} |",
          f"| Completed | {nv('Year Completed') or 'n/a'} |",
          f"| Height | {_fmt(float(nv('NID Height (Ft)')) if nv('NID Height (Ft)') else None)} ft |",
          f"| Drainage area | {_fmt(float(nv('Drainage Area (Sq Miles)')) if nv('Drainage Area (Sq Miles)') else None)} sq mi |",
          f"| Hazard class | {nv('Hazard Potential Classification') or 'n/a'} |",
          f"| Dam registry capacity | {_fmt(float(nv('NID Storage (Acre-Ft)')) if nv('NID Storage (Acre-Ft)') else None)} af maximum, "
          f"{_fmt(float(nv('Normal Storage (Acre-Ft)')) if nv('Normal Storage (Acre-Ft)') else None)} af normal. "
          "Owner-reported and not corrected for sediment; not used as a denominator unless stated. |",
          f"| National Inventory of Dams id | {cfg.get('nid_id')} |", ""]

    L += ["## How to use this data", ""] + [f"- {u}" for u in cfg.get("uses", [])] + [""]
    L += ["## Read before quoting a number", ""] + [f"- {c}" for c in ROLE_CAUTION.get(cfg["role"], [])] \
        + [f"- {c}" for c in cfg.get("cautions", [])] + [""]

    # provenance
    L += ["## Data provenance", "", "| Series | Site | Observations (daily) | From | To |", "|---|---|---|---|---|"]
    raw = r["raw"]
    used = set(r["stor"].site_uid.unique()) if "site_uid" in r["stor"] else set()
    for (site, var), gg in raw.groupby(["site_uid", "variable"]):
        lab = "release (gauge below dam)" if site in (cfg.get("release_gauges") or []) else var.replace("reservoir_", "")
        L.append(f"| {lab} | `{site}` | {len(gg):,} | {pd.Timestamp(gg.date.min()).date()} | "
                 f"{pd.Timestamp(gg.date.max()).date()} |")
    L += [""]
    days = r["stor"].groupby("site_uid").size().sort_values(ascending=False)
    if len(days) > 1:
        L += ["Storage is spliced day by day in registry priority order. Days taken from each site: "
              + ", ".join(f"`{s}` {c:,}" for s, c in days.items()) + ".", ""]
        ov = _overlap(raw, list(cfg["sites"]))
        if ov:
            L += ["Agreement where sites overlap, median absolute difference in storage: "
                  + "; ".join(ov) + ".", ""]
    if cfg.get("release_gauges"):
        L += ["Release is taken first from the USGS gauge just below the dam ("
              + ", ".join(f"`{g}`" for g in cfg["release_gauges"]) + "), which measures what actually "
              "leaves the reservoir plus minor local inflow and has a longer record than the operator's "
              "reported release; the reported release fills days the gauge lacks.", ""]
    if cfg.get("start_year"):
        L += [f"Years before {cfg['start_year']} are excluded: {cfg.get('start_year_reason', 'the dam was not yet in operation')}.", ""]
    srcs = sorted({s.split(":")[0] for s in raw.site_uid.unique()})
    L += ["Sources:", ""] + [f"- {SOURCE_CITES[s][0]}, `{SOURCE_CITES[s][1]}`, accessed 2026." for s in srcs if s in SOURCE_CITES] + [""]
    _ = used

    # capacity
    L += ["## Capacity and pools", ""]
    rm, v = r["rating"], r["valid"]
    ov = cfg.get("capacity_basis_override")
    if ov:
        L += [f"**No validated operator table.** Percentages are against {_fmt(ov['af'])} acre-feet, the "
              f"{ov['source']}. Storage figures themselves are the operator's and are unaffected.", ""]
        if rm:
            L += [f"An operator table exists in CWMS (`{rm['rating_id']}`, effective {rm['effective_date']}), but without "
                  "an elevation series it cannot be validated or used.", ""]
    elif rm:
        L += [f"**Capacity table:** `{rm['rating_id']}` from the Corps' CWMS, the operator's current elevation-to-storage "
              f"table, maintained by {rm['agency'] or 'the operator'}, effective {rm['effective_date']}, elevations in "
              f"{rm['datum'] or 'the project datum (unstated)'}. {rm['n_points']:,} points from "
              f"{_fmt(rm['elev_min'], 2)} to {_fmt(rm['elev_max'], 2)} ft, {_fmt(rm['stor_max'])} acre-feet at the top.", ""]
        if rm.get("description"):
            L += [f"Table note: _{rm['description']}_", ""]
        if v:
            L += [f"**Validation.** Since {v['since']}, looking up each day's reported elevation in this table reproduces "
                  f"reported storage to a median of {_fmt(v['median_abs_af'], 1)} acre-feet "
                  f"({v['median_rel_pct']:.2f}%), 95th percentile {_fmt(v['p95_abs_af'], 1)} acre-feet, over "
                  f"{v['n']:,} days.", ""]
        if float(cfg.get("elev_shift_ft", 0)):
            L += [f"Observed elevations are shifted {cfg['elev_shift_ft']:+.2f} ft before lookup.", ""]
        acap = con.execute("select any_value(item_id) i, any_value(survey_label) s, max(capacity_af) c "
                           "from reservoir_acap where reservoir ilike ?", [f"%{cfg['name'].split()[0]}%"]).fetchone()
        if acap and acap[0]:
            L += [f"Reclamation's sedimentation-survey table (RISE catalog item {acap[0]}, survey {acap[1]}) is also in "
                  "the archive as `reservoir_acap` and serves as corroboration; the CWMS table is used because it is "
                  "what the operator computes storage with today.", ""]
    if r["pools"]:
        L += ["**Pools.** Pools are defined by elevation; capacity is looked up in the current table, so it changes "
              "when the table does. The published storage for each level, where the Corps records one, is shown "
              "for comparison and often comes from an older table.", "",
              "| Pool | Elevation (ft) | Capacity, current table (af) | Published level storage (af) | Source |",
              "|---|---|---|---|---|"]
        for p in r["pools"]:
            L.append(f"| {POOL_LABEL.get(p['pool'], p['pool'])} | {_fmt(p['elev_ft'], 2)} | {_fmt(p['capacity_current_af'])} | "
                     f"{_fmt(p['level_storage_af'])} | {p['source']}"
                     + (f"; _{p['comment'].strip()}_" if p.get("comment") else "") + " |")
        L += [""]
    h = r.get("hist")
    if h is not None and len(h):
        L += ["**Published pool capacity history.** The operator records this pool's capacity under successive "
              "tables or entitlements. From each date below, that published figure is used as the denominator "
              "instead of the derived capacity, and those years carry the confidence `published_pool`. A level "
              "dated 1900-01-01 is the as-built figure and applies from the start of the record.", "",
              "| From | Capacity (af) | Note |", "|---|---|---|"]
        for x in h.itertuples():
            L.append(f"| {x.from_date.date()} | {_fmt(x.af)} | {x.note or ''} |")
        L += [""]
    if r["primary"]:
        L += [f"**Full pool used for percentages:** {POOL_LABEL.get(r['primary']['pool'], r['primary']['pool']).lower()}, "
              f"{_fmt(r['primary']['elev_ft'], 2)} ft."
              + (f" **Flood pool:** top of flood control, {_fmt(r['flood']['elev_ft'], 2)} ft." if r["flood"] else ""), ""]

    # method specifics
    e = r["eras"]
    if len(e):
        how = "forced from the reviewed adoption dates in the registry" if cfg.get("era_boundaries") else \
            "detected by comparing each year with the previous one over the elevations both occupied"
        L += ["## Capacity history", "",
              f"Reported storage departs from the current table in earlier years because older tables were in force. "
              f"{len(e)} table {'era was' if len(e) == 1 else 'eras were'} found, {how}. Departure is the median of reported storage minus the current "
              "table's storage at the same elevation. Capacities are at today's pool elevations"
              + (", so where a published pool capacity history exists above it takes precedence for percentages."
                 if h is not None and len(h) else "."), ""]
        pcols = [c[:-3] for c in e.columns if c.endswith("_af") and not c.endswith("_raw_af") and c != "median_departure_af"]
        hdr = "| Era | Dates | Elevation range (ft) | Departure (af) | " + " | ".join(
            f"{POOL_LABEL.get(pc, pc)} capacity (af), confidence" for pc in pcols) + " |"
        L += [hdr, "|" + "---|" * (4 + len(pcols))]
        for row in e.itertuples():
            cells = [f"{_fmt(getattr(row, pc + '_af'))}, {getattr(row, pc + '_confidence')}" for pc in pcols]
            L.append(f"| {row.label} | {row.first_date} to {row.last_date} | {row.min_elev_ft}-{row.max_elev_ft} | "
                     f"{_fmt(row.median_departure_af)} | " + " | ".join(cells) + " |")
        L += ["", "Confidence: `current_table` means reported storage reproduces from the current table; `high` means "
              "the lake reached the pool elevation during that era, or came within 10 ft; `medium` within 30 ft; "
              "`low` farther, or the monotone fit had to move the estimate more than 2%.", ""]
        first_cap, last_cap = e[f"{pcols[0]}_af"].iloc[0], e[f"{pcols[0]}_af"].iloc[-1]
        if first_cap and first_cap > last_cap:
            L += [f"Capacity of the {POOL_LABEL.get(pcols[0], pcols[0]).lower()} fell from {_fmt(first_cap)} to "
                  f"{_fmt(last_cap)} acre-feet over the record, {100 * (1 - last_cap / first_cap):.0f}%.", ""]
    elif not ov:
        L += ["## Capacity history", "", "No elevation-paired record long enough to identify earlier tables; every year "
              "is measured against the current table.", ""]

    L += _highlights(r)
    return "\n".join(L).rstrip() + "\n"


ACRONYMS = {"USACE", "DOI", "BLM", "BIA", "NM", "USBR", "US", "ISC"}
SMALL = {"of", "and", "the", "for", "de"}


def _owner(v) -> str:
    if not v or (isinstance(v, float) and math.isnan(v)):
        return "n/a"
    words = []
    for i, w in enumerate(str(v).split()):
        if w.upper() in ACRONYMS:
            words.append(w.upper())
        elif w.lower() in SMALL and i:
            words.append(w.lower())
        else:
            words.append("-".join(p.capitalize() for p in w.split("-")))
    return " ".join(words)


def _overlap(raw: pd.DataFrame, sites: list[str]) -> list[str]:
    s = raw[raw.variable == "reservoir_storage"]
    out = []
    for a_, b_ in pairwise(sites):
        m = s[s.site_uid == a_][["date", "value"]].merge(s[s.site_uid == b_][["date", "value"]], on="date")
        if len(m) >= 30:
            d = (m.value_x - m.value_y).abs()
            out.append(f"`{a_}` vs `{b_}` {d.median():,.0f} af over {len(m):,} shared days")
    return out


def _highlights(r: dict) -> list[str]:
    a = r["annual"]
    full = a[a.n_days >= 330]
    if full.empty:
        return []
    L = ["## What the record shows", "",
         f"Record: {a.year.min()} to {a.year.max()}, {len(a)} years, {int(a.n_days.sum()):,} days of storage.", ""]
    role = r["cfg"]["role"]
    if role == "dry_flood":
        thr = dry_threshold(float(a.flood_pool_af.max()) if "flood_pool_af" in a else 0.0)
        top = full[full.peak_af > thr].nlargest(5, "peak_af")
        L += [f"Largest flood-storage years, by peak storage (a flood is storage above {thr:,.0f} af): " + "; ".join(
            f"{int(x.year)} {_fmt(x.peak_af)} af on {x.peak_date}"
            + (f" ({x.peak_flood_pct:.1f}% of the flood pool)" if "peak_flood_pct" in a and pd.notna(x.peak_flood_pct) else "")
            for x in top.itertuples()) + ".", ""]
        if "days_flood_storage" in a:
            L += [f"Years with any flood storage: {int((a.days_flood_storage > 0).sum())} of {len(a)}.", ""]
    elif role == "flood_control":
        if "peak_flood_pct" in a:
            fy = full[full.days_flood_storage > 0].nlargest(5, "peak_flood_pct")
            if len(fy):
                L += ["Largest use of the flood pool: " + "; ".join(
                    f"{int(x.year)} peaking at {x.peak_flood_pct:.1f}% of flood capacity on {x.peak_date}, "
                    f"{int(x.days_flood_storage)} days above the conservation pool" for x in fy.itertuples()) + ".", ""]
            L += [f"Years holding flood water: {int((full.days_flood_storage > 0).sum())} of {len(full)} complete years.", ""]
        lo = full.nsmallest(3, "low_pct")
        L += ["Lowest conservation storage, by annual low: " + "; ".join(
            f"{int(x.year)} {x.low_pct:.1f}%" for x in lo.itertuples()) + ".", ""]
        if len(full) >= 20:
            f10, l10 = full.head(10).mean_pct.mean(), full.tail(10).mean_pct.mean()
            L += [f"Average annual mean storage as a share of the conservation pool: {f10:.1f}% over the first ten "
                  f"complete years, {l10:.1f}% over the last ten. Values above 100% include flood storage.", ""]
    else:
        if full.peak_pct.notna().any():
            hi = full.nlargest(3, "peak_pct")
            lo = full.nsmallest(3, "peak_pct")
            L += ["Fullest years, by annual peak: " + "; ".join(f"{int(x.year)} {x.peak_pct:.1f}%" for x in hi.itertuples()) + ".",
                  "", "Emptiest years, by annual peak: " + "; ".join(f"{int(x.year)} {x.peak_pct:.1f}%" for x in lo.itertuples()) + ".", ""]
            if len(full) >= 20:
                f10, l10 = full.head(10).mean_pct.mean(), full.tail(10).mean_pct.mean()
                L += [f"Average annual mean fill: {f10:.1f}% over the first ten complete years, {l10:.1f}% over the last ten.", ""]
    if "inflow_af" in a and a.inflow_af.notna().sum() >= 5:
        iv = a.dropna(subset=["inflow_af"])
        L += [f"Annual inflow, complete years: median {_fmt(iv.inflow_af.median())} af, largest {_fmt(iv.inflow_af.max())} "
              f"af in {int(iv.loc[iv.inflow_af.idxmax(), 'year'])}, smallest {_fmt(iv.inflow_af.min())} af in "
              f"{int(iv.loc[iv.inflow_af.idxmin(), 'year'])}.", ""]
    if "peak_release_cfs" in a and a.peak_release_cfs.notna().any():
        rv = a.dropna(subset=["peak_release_cfs"]).nlargest(3, "peak_release_cfs")
        lab = "measured below the dam" if r["cfg"].get("release_gauges") else "reported"
        L += [f"Highest daily releases, {lab}: " + "; ".join(f"{_fmt(x.peak_release_cfs)} cfs on {x.peak_release_date}"
                                                    for x in rv.itertuples()) + ".", ""]
    last = a.iloc[-1]
    L += [f"{int(last.year)} so far ({int(last.n_days)} days): peak {_fmt(last.peak_af)} af"
          + (f", {last.peak_pct:.1f}% of full pool" if pd.notna(last.get('peak_pct')) else "")
          + f"; latest low {_fmt(last.low_af)} af.", ""]
    return L


ROLE_TEXT = {
    "storage": "Storage reservoir: holds water for later release.",
    "flood_control": "Flood control with a conservation or recreation pool beneath a much larger flood pool.",
    "dry_flood": "Dry flood control: no permanent pool; stores water only while holding back a flood.",
    "diversion": "Diversion forebay for irrigation canals, routinely drawn down.",
    "municipal": "Municipal water supply.",
}
ROLE_CAUTION = {
    "flood_control": ["This is a flood-control dam. Percent full is measured against the conservation pool, which "
                      "is what the dam normally holds. Storage above it is flood water being held back, measured "
                      "by `days_flood_storage` and `peak_flood_pct`. Dividing storage by the dam's total or design "
                      "capacity answers a different question and will read very low."],
    "dry_flood": ["This is a dry dam. It is empty by design, and percent full is measured against the flood pool, "
                  "so small numbers are normal. Peak storage, `days_flood_storage` and `peak_flood_pct` carry the "
                  "signal: each is a flood being held."],
    "diversion": ["This is a diversion forebay. Low storage usually reflects canal operations, not dry conditions."],
}
POOL_LABEL = {"full": "Full pool", "conservation": "Top of conservation", "flood": "Top of flood control",
              "spillway": "Spillway crest", "dam": "Top of dam", "entitlement": "Top of entitlement",
              "inactive": "Top of inactive"}


BASIS_TEXT = {"table": "operator table, validated", "owner": "dam registry normal storage (not validated)"}


def _nv(n: dict, k: str) -> str:
    v = n.get(k)
    return "n/a" if v is None or (isinstance(v, float) and math.isnan(v)) else str(v)


def _index_row(r: dict, nid: dict) -> dict:
    cfg, a = r["cfg"], r["annual"]
    n = nid.get(cfg.get("nid_id"), {})
    last = a.iloc[-1]
    full = a[a.n_days >= 330]
    basis = "owner" if cfg.get("capacity_basis_override") else "table"
    return {"key": r["key"], "name": cfg["name"], "basin": cfg["basin"], "role": cfg["role"],
            "type": _nv(n, "Primary Dam Type"), "purpose": _nv(n, "Primary Purpose"),
            "owner": _owner(n.get("Owner Names")), "completed": _nv(n, "Year Completed"),
            "first": int(a.year.min()), "last": int(a.year.max()), "basis": BASIS_TEXT[basis],
            "full_af": last.get("full_pool_af"), "last_year": int(last.year), "last_peak_pct": last.get("peak_pct"),
            "median_peak_pct": float(full.peak_pct.median()) if len(full) and "peak_pct" in full else float("nan")}


ROLE_SHORT = {"storage": "storage", "flood_control": "flood control + conservation pool",
              "dry_flood": "dry flood control", "diversion": "diversion forebay", "municipal": "municipal supply"}


def render_index(rows: list[dict]) -> str:
    L = ["# Reservoir reports", "",
         "_Generated by `scripts/reservoir_fill.py`. Method, columns and caveats: "
         "[../reservoir-fill.md](../reservoir-fill.md)._", "",
         "Each reservoir has its own notes file covering the dam, how its data can be used, data provenance, "
         "capacity source and pool definitions, capacity history, and what the record shows. Read the one for the "
         "reservoir you are quoting: several carry warnings that change what a percentage means.", "",
         "| Reservoir | Basin | Dam type | Primary purpose (registry) | How it is operated | Owner | Completed | "
         "Record | Capacity basis | Full pool (af) | Median annual peak | Latest peak |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for x in rows:
        L.append(f"| [{x['name']}]({x['key']}.md) | {x['basin']} | {x['type']} | {x['purpose']} | "
                 f"{ROLE_SHORT[x['role']]} | {x['owner']} | {x['completed']} | {x['first']}-{x['last']} | "
                 f"{x['basis']} | {_fmt(x['full_af'])} | {_fmt(x['median_peak_pct'], 1)}% | "
                 f"{_fmt(x['last_peak_pct'], 1)}% ({x['last_year']}) |")
    L += ["", "Percentages are against the full pool: the conservation pool for flood-control dams (so "
          "values above 100% include flood storage), the flood pool for dry dams (so small values are normal), "
          "and the owner-reported normal storage where no operator table can be validated. The latest year is "
          "partial.", ""]
    return "\n".join(L)


# ---------------------------------------------------------------------------- main
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--db", default=str(ROOT / "data" / "duckdb" / "nmwater.duckdb"))
    ap.add_argument("--out", default=str(ROOT / "reports"))
    ap.add_argument("--notes", default=str(ROOT / "docs" / "reports" / "reservoirs"))
    ap.add_argument("--only", nargs="*")
    ap.add_argument("--no-notes", action="store_true")
    args = ap.parse_args()
    reg = yaml.safe_load(REGISTRY.read_text())["reservoirs"]
    con = connect(args.db)
    nid = load_nid()
    out, notes = Path(args.out), Path(args.notes)
    (out / "reservoirs").mkdir(parents=True, exist_ok=True)
    notes.mkdir(parents=True, exist_ok=True)
    ann, eras, pools, index = [], [], [], []
    for key, cfg in reg.items():
        if args.only and key not in args.only:
            continue
        r = build(con, key, cfg)
        a = r["annual"]
        a.to_csv(out / "reservoirs" / f"{key}_annual_fill.csv", index=False)
        ann.append(a)
        if len(r["eras"]):
            eras.append(r["eras"])
        pools += r["pools"]
        if not args.no_notes:
            (notes / f"{key}.md").write_text(render_notes(con, r, nid))
        index.append(_index_row(r, nid))
        v = r["valid"]
        vtxt = f"{v['median_abs_af']:.1f} af median" if v else "-"
        peak = a.peak_pct.iloc[-1] if "peak_pct" in a else float("nan")
        print(f"{key:<15} {a.year.min()}-{a.year.max()} {len(a):>3} yrs  eras {len(r['eras']):>2}  "
              f"validation {vtxt:>16}  latest peak {peak:>6.1f}%")
    if args.only:
        return
    pd.concat(ann, ignore_index=True).to_csv(out / "reservoir_annual_fill.csv", index=False)
    pd.concat(eras, ignore_index=True).to_csv(out / "reservoir_capacity_eras.csv", index=False)
    pd.DataFrame(pools).to_csv(out / "reservoir_pools.csv", index=False)
    if not args.no_notes:
        (notes / "index.md").write_text(render_index(index))
    print(f"wrote {len(ann)} reservoirs to {out}")


if __name__ == "__main__":
    main()
